// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Api.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("PublicId");

                    b.Property<string>("Url");

                    b.Property<string>("UsuarioCedula");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCedula");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("Api.Models.Usuario", b =>
                {
                    b.Property<string>("Cedula")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Creado");

                    b.Property<byte[]>("Hash");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreCompleto");

                    b.Property<byte[]>("Salt");

                    b.Property<DateTime>("UltimoLog");

                    b.HasKey("Cedula");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Api.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Api.Models.Foto", b =>
                {
                    b.HasOne("Api.Models.Usuario", "Usuario")
                        .WithMany("Fotos")
                        .HasForeignKey("UsuarioCedula");
                });
#pragma warning restore 612, 618
        }
    }
}
